name: Build iOS app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Build
    runs-on: macos-14
    # Only run build in template repo
    # if: github.event.repository.name == 'KMP-App-Template' && github.repository_owner == 'Kotlin'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: iOS debug build
        run: xcodebuild -workspace iosApp/iosApp.xcodeproj/project.xcworkspace -configuration Debug -scheme iosApp -sdk iphonesimulator
